export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SEARCH = "GET_CURRENT_USER_SEARCH";
export const POST_CURRENT_USER_WATCHLIST = "POST_CURRENT_USER_WATCHLIST";